/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-17 05:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>글읽</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>[글읽기]</h1>\r\n");
      out.write("<form action=\"update\" method=\"post\" name=\"frm\">\r\n");
      out.write("<input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<table border=1>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Title</td>\r\n");
      out.write("\t\t\t<td width=500><input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Writer</td>\r\n");
      out.write("\t\t\t<td width=500><input type=\"text\" name=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Content</td>\r\n");
      out.write("\t\t\t<td width=500><textarea rows=\"10\" cols=\"50\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("</table>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"저장\">\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"삭제\" id=\"btnDelete\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"목록\" onClick=\"location.href='list' \">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"upload\">\r\n");
      out.write("\t\t\t\t<input type=\"file\" id=\"file\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h1>[첨부 파일목록]</h1>\r\n");
      out.write("\t\t\t<div id=\"uploaded\">\r\n");
      out.write("\t\t\t\t<ul id=\"uploadedFiles\"></ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\"#file\").on(\"change\",function(){\r\n");
      out.write("\tvar file=$(\"#file\")[0].files[0];\r\n");
      out.write("\tif(file==null) return;\r\n");
      out.write("\tvar formData=new FormData();\r\n");
      out.write("\tformData.append(\"file\",file);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("              type:\"post\",\r\n");
      out.write("              url:\"/uploadFile\",\r\n");
      out.write("              processData:false,\r\n");
      out.write("              contentType:false,\r\n");
      out.write("              data:formData,\r\n");
      out.write("              success:function(data){\r\n");
      out.write("                 \r\n");
      out.write("                 var str=\"<li>\";\r\n");
      out.write("                 str+=\"<img src=/displayFile?fileName=\"+data+\" width=100 />\"\r\n");
      out.write("                 str+= \"<input type=text name='files' value='\"+data+\"'>\";\r\n");
      out.write("                 str+=\"<a href='\"+data+\"'>삭제</a>\";\r\n");
      out.write("                 str+=\"</li>\";\r\n");
      out.write("                 $(\"#uploadedFiles\").append(str);\r\n");
      out.write("              }\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//업로드 삭제\r\n");
      out.write("\r\n");
      out.write("$(\"#uploadedFiles\").on(\"click\",\"a\",function(e){\r\n");
      out.write("\r\n");
      out.write("\te.preventDefault();\r\n");
      out.write(" var fileName=$(this).attr(\"href\");\r\n");
      out.write(" var li=$(this).parent();\r\n");
      out.write(" \r\n");
      out.write(" $.ajax({\r\n");
      out.write("type:\"post\",\r\n");
      out.write("url:\"/deleteFile\",\r\n");
      out.write("data:{\"fileName\":fileName},\r\n");
      out.write("success:function(){\r\n");
      out.write("\tli.remove();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write(" })\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("getAttach();\r\n");
      out.write("function getAttach(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"getAttach.json\",\r\n");
      out.write("\t\tdata:{\"bno\":bno},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$(data).each(function(){\r\n");
      out.write("\t\t\t\t  var str=\"<li>\";\r\n");
      out.write("\t                 str+=\"<img src=/displayFile?fileName=\"+this+\" width=100 />\"\r\n");
      out.write("\t                 str+= \"<input type=text name='files' value='\"+this+\"'>\";\r\n");
      out.write("\t                 str+=\"<a href='\"+this+\"'>삭제</a>\";\r\n");
      out.write("\t                 str+=\"</li>\";\r\n");
      out.write("\t                 $(\"#uploadedFiles\").append(str);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#btnDelete\").on(\"click\", function(){\r\n");
      out.write("\tif(!confirm(\"삭제하실래요?\")) return;\r\n");
      out.write("\tfrm.action=\"delete\";\r\n");
      out.write("\tfrm.submit();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" $(frm).submit(function(e){\r\n");
      out.write("\t e.preventDefault();\r\n");
      out.write("\t if($(frm.title).val()==\"\"){\r\n");
      out.write("\t\t alert(\"제목을 입력하세요!\");\r\n");
      out.write("\t\t $(frm.title).focus();\r\n");
      out.write("\t }if($(frm.content).val()==\"\"){\r\n");
      out.write("\t\t alert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t $(frm.content).focus();\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t if(!confirm(\"글을 수정하실래요?\")) return;\r\n");
      out.write("\t\t frm.submit();\r\n");
      out.write("\t }\r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
