/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-17 04:29:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajaxUpload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("         <h1>[파일업로드 Ajax]</h1>\r\n");
      out.write("         <div id =\"upload\">\r\n");
      out.write("          <input type=\"file\" id=\"file\">\r\n");
      out.write("          <img>\r\n");
      out.write("         </div>\r\n");
      out.write("         <hr>\r\n");
      out.write("         <div id=\"uploaded\">\r\n");
      out.write("         <ul id=\"uploadedFiles\"></ul>\r\n");
      out.write("         </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#file\").on(\"change\",function(){\r\n");
      out.write("\tvar file=$(\"#file\")[0].files[0];\r\n");
      out.write("\tif(file==null) return;\r\n");
      out.write("\tvar formData=new FormData();\r\n");
      out.write("\tformData.append(\"file\",file);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("              type:\"post\",\r\n");
      out.write("              url:\"/uploadFile\",\r\n");
      out.write("              processData:false,\r\n");
      out.write("              contentType:false,\r\n");
      out.write("              data:formData,\r\n");
      out.write("              success:function(data){\r\n");
      out.write("                 \r\n");
      out.write("                 var str=\"<li>\";\r\n");
      out.write("                 str+=\"<img src=/displayFile?fileName=\"+data+\" width=100 />\"\r\n");
      out.write("                 str+= \"<input type=text name='files' value='\"+data+\"'>\";\r\n");
      out.write("                 str+=\"<a href='\"+data+\"'>삭제</a>\";\r\n");
      out.write("                 str+=\"</li>\";\r\n");
      out.write("                 $(\"#uploadedFiles\").append(str);\r\n");
      out.write("              }\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//업로드 삭제\r\n");
      out.write("\r\n");
      out.write("$(\"#uploadedFiles\").on(\"click\",\"a\",function(e){\r\n");
      out.write("\r\n");
      out.write("\te.preventDefault();\r\n");
      out.write(" var fileName=$(this).attr(\"href\");\r\n");
      out.write(" var li=$(this).parent();\r\n");
      out.write(" \r\n");
      out.write(" $.ajax({\r\n");
      out.write("type:\"post\",\r\n");
      out.write("url:\"/deleteFile\",\r\n");
      out.write("data:{\"fileName\":fileName},\r\n");
      out.write("success:function(){\r\n");
      out.write("\tli.remove();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write(" })\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
